services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clouderp
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d clouderp']
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      PORT: 5010
      DATABASE_URL: postgresql://postgres:postgres@db:5432/clouderp
      JWT_SECRET: change-me
      PRISMA_HIDE_UPDATE_MESSAGE: '1'
      PRISMA_DISABLE_TELEMETRY: '1'
      WEB_ORIGIN: http://localhost:3000
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '5010:5010'

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://api:5010
    depends_on:
      - api
    ports:
      - '3000:3000'

volumes:
  pgdata:
